version: '3'
services:
  app:
    build: .
    command: flask run --port=5050
    ports:
      - "5050:5050"
    depends_on:
      - neo4j
    volumes:
      - ./:/app
  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/12345678
      - NEO4JLABS_PLUGINS='["graph-data-science"]'
    ports:
      - "7687:7687"
      - "7474:7474"
    volumes:
      - ./neo4j/plugins:/plugins
      - ./neo4j/data:/data
      - ./neo4j/neo4j.dump:/var/lib/neo4j/import/neo4j.dump
    command: >
      bash -c "
        while ! nc -z localhost 7687; do sleep 1; done;
        if [ -f /data/databases/neo4j/neostore ]; then
          echo 'Database already exists, skipping import.'
        else
          echo 'Importing database from dump...'
          neo4j-admin load --from=/var/lib/neo4j/import/neo4j.dump --database=neo4j --force
        fi
        /docker-entrypoint.sh neo4j
      "